# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
        # Descargar el repo al directorio de trabajo
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "cmiautorizo-backend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd cmiautorizo-backend
      - run: cd cmiautorizo-backend && npm install

      - save_cache:
          paths:
            - cmiautorizo-backend/node_modules
          key: v1-dependencies-{{ checksum "cmiautorizo-backend/package.json" }}

      # run tests!
      - run: cd cmiautorizo-backend && npm run test